export const CHAT_DATA_REQUEST = 'CHAT_DATA_REQUEST';
export const CHAT_DATA_SUCCESS = 'CHAT_DATA_SUCCESS';
export const CHAT_DATA_FAIL = 'CHAT_DATA_FAIL';

export const CURRENT_CHAT_DATA_REQUEST = 'CURRENT_CHAT_DATA_REQUEST';
export const CURRENT_CHAT_DATA_SUCCESS = 'CURRENT_CHAT_DATA_SUCCESS';
export const CURRENT_CHAT_DATA_FAIL = 'CURRENT_CHAT_DATA_FAIL';

export const SEND_NEW_CHAT_DATA_REQUEST = 'SEND_NEW_CHAT_DATA_REQUEST';
export const SEND_NEW_CHAT_DATA_SUCCESS = 'SEND_NEW_CHAT_DATA_SUCCESS';
export const SEND_NEW_CHAT_DATA_FAIL = 'SEND_NEW_CHAT_DATA_FAIL';
