export const CURRENT_USER_SET_REQUEST = 'CURRENT_USER_SET_REQUEST';
export const CURRENT_USER_SET_SUCCESS = 'CURRENT_USER_SET_SUCCESS';
export const CURRENT_USER_SET_FAIL = 'CURRENT_USER_SET_FAIL';

export const USER_PROFILE_SET_REQUEST = 'USER_PROFILE_SET_REQUEST';
export const USER_PROFILE_SET_SUCCESS = 'USER_PROFILE_SET_SUCCESS';
export const USER_PROFILE_SET_FAIL = 'USER_PROFILE_SET_FAIL';
